node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('Install') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('Test') {
    nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm test'
     }
   }
   stage('Address Non attention issues') {
    nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm audit fix --force'
     }
   }
   stage('docker build') {
      
      echo "Docker Future"
      
   }
   stage('Complete') {
        echo "Build Complete"
        
   }
}
